version: '3.9'

services:
  demo-race:
    container_name: demo-race
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:3000"
    restart: always
    environment:
      NODE_ENV: production