name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/demo-race:latest .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/demo-race:latest

      - name: Connect to VPS and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/demo-race/f1-gp-david

            # Pull latest code
            git pull

            # Stop and remove old container
            docker stop demo-race || true
            docker rm demo-race || true

            # Pull latest image from GHCR
            docker pull ghcr.io/${{ github.repository}}/demo-race:latest

            # Run new container
            docker run -d --name demo-race -p 8083:3000 ghcr.io/${{ github.repository }}/demo-race:latest

            # Cleanup old images
            docker image prune -f
